name: Deploy to ECS

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # 3. Install jq (IMPORTANT)
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # 4. Login to ECR
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 \
          | docker login --username AWS \
          --password-stdin 084928383265.dkr.ecr.ap-south-1.amazonaws.com

      # 5. Build Docker image with unique tag
      - name: Build Docker image
        run: docker build -t my-app:${{ github.sha }} .

      # 6. Tag image for ECR
      - name: Tag image
        run: docker tag my-app:${{ github.sha }} 084928383265.dkr.ecr.ap-south-1.amazonaws.com/my-app:${{ github.sha }}

      # 7. Push image to ECR
      - name: Push image
        run: docker push \
          084928383265.dkr.ecr.ap-south-1.amazonaws.com/my-app:${{ github.sha }}

      # 8. Update ECS Task Definition
      - name: Update ECS Task Definition
        run: |
          aws ecs describe-task-definition \
            --task-definition app \
            --query taskDefinition > task-def.json

          cat task-def.json | jq 'del(
            .taskDefinitionArn,
            .revision,
            .status,
            .requiresAttributes,
            .compatibilities,
            .registeredAt,
            .registeredBy
          ) | .containerDefinitions[0].image="084928383265.dkr.ecr.ap-south-1.amazonaws.com/my-app:${{ github.sha }}"' > new-task-def.json

          aws ecs register-task-definition \
            --cli-input-json file://new-task-def.json

      # 9. Deploy latest revision to ECS
      - name: Deploy to ECS
        run: |
          NEW_REVISION=$(aws ecs list-task-definitions \
            --family-prefix app \
            --sort DESC \
            --max-items 1 \
            --query 'taskDefinitionArns[0]' \
            --output text)

          aws ecs update-service \
            --cluster my-cluster \
            --service app-service-lc2cue16 \
            --task-definition $NEW_REVISION \
            --region ap-south-1